[2025-05-17T06:01:32.548+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: uhi_index_analytics_pipeline_decompose.create_spark_session manual__2025-05-17T05:12:03.413965+00:00 [queued]>
[2025-05-17T06:01:32.568+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: uhi_index_analytics_pipeline_decompose.create_spark_session manual__2025-05-17T05:12:03.413965+00:00 [queued]>
[2025-05-17T06:01:32.568+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-05-17T06:01:32.570+0000] {taskinstance.py:1280} INFO - Starting attempt 4 of 4
[2025-05-17T06:01:32.570+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-05-17T06:01:32.595+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): create_spark_session> on 2025-05-17 05:12:03.413965+00:00
[2025-05-17T06:01:32.609+0000] {standard_task_runner.py:55} INFO - Started process 78 to run task
[2025-05-17T06:01:32.613+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'uhi_index_analytics_pipeline_decompose', 'create_spark_session', 'manual__2025-05-17T05:12:03.413965+00:00', '--job-id', '189', '--raw', '--subdir', 'DAGS_FOLDER/uhi_pipeline_dag_decompose.py', '--cfg-path', '/tmp/tmpv4cefsy8']
[2025-05-17T06:01:32.614+0000] {standard_task_runner.py:83} INFO - Job 189: Subtask create_spark_session
[2025-05-17T06:01:32.740+0000] {task_command.py:388} INFO - Running <TaskInstance: uhi_index_analytics_pipeline_decompose.create_spark_session manual__2025-05-17T05:12:03.413965+00:00 [running]> on host 440290e0e309
[2025-05-17T06:01:32.852+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uhi_index_analytics_pipeline_decompose
AIRFLOW_CTX_TASK_ID=create_spark_session
AIRFLOW_CTX_EXECUTION_DATE=2025-05-17T05:12:03.413965+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-05-17T05:12:03.413965+00:00
[2025-05-17T06:01:33.223+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/uhi_pipeline_dag_decompose.py", line 44, in create_spark_session
    spark = spark_session.create_spark_session()
  File "/opt/airflow/project_code/data_pipeline_test/spark_session.py", line 69, in create_spark_session
    spark_session = builder.getOrCreate()
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/sql/session.py", line 477, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/context.py", line 512, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/context.py", line 198, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/context.py", line 432, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/java_gateway.py", line 106, in launch_gateway
    raise RuntimeError("Java gateway process exited before sending its port number")
RuntimeError: Java gateway process exited before sending its port number
[2025-05-17T06:01:33.242+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=uhi_index_analytics_pipeline_decompose, task_id=create_spark_session, execution_date=20250517T051203, start_date=20250517T060132, end_date=20250517T060133
[2025-05-17T06:01:33.266+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 189 for task create_spark_session (Java gateway process exited before sending its port number; 78)
[2025-05-17T06:01:33.305+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-05-17T06:01:33.353+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
